/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register
         * @description Public self-signup: create a student account and log them straight in.
         *
         *     Always creates role=student — the teacher account is provisioned separately.
         *     NOTE (flagged, not yet built): this endpoint has no email verification and no
         *     rate limiting. Both should land before any real public launch — see
         *     docs/SoW §5. Deliberately minimal for the first self-serve pass.
         */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_auth_students_get"];
        put?: never;
        /**
         * Create Student
         * @description There is no self-signup — only the teacher creates student accounts.
         */
        post: operations["create_student_auth_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List My Decks
         * @description Every deck in the student's study loop: teacher-assigned ("class") decks and
         *     the personal decks they authored themselves. `owned` distinguishes the two.
         */
        get: operations["list_my_decks_decks_get"];
        put?: never;
        /**
         * Create My Deck
         * @description Create a personal deck and drop it straight into the student's own study
         *     loop by self-assigning it — the same Assignment mechanism the teacher uses, so
         *     the SRS engine needs no special case for personal decks.
         */
        post: operations["create_my_deck_decks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete My Deck
         * @description Delete a personal deck and its cards. Blocked once any card has been
         *     graded — `reviews` is an append-only log we never destroy.
         */
        delete: operations["delete_my_deck_decks__deck_id__delete"];
        options?: never;
        head?: never;
        /** Rename My Deck */
        patch: operations["rename_my_deck_decks__deck_id__patch"];
        trace?: never;
    };
    "/decks/{deck_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Deck Cards */
        get: operations["list_deck_cards_decks__deck_id__cards_get"];
        put?: never;
        /**
         * Add Card To My Deck
         * @description Add a card to a deck the student owns. `source` is forced to `manual` — the
         *     AI enrichment path stays teacher-only (cost/abuse), so a student can't route
         *     through here to tag AI content.
         */
        post: operations["add_card_to_my_deck_decks__deck_id__cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/decks/{deck_id}/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Card In My Deck
         * @description Delete a card from a deck the student owns. Blocked once it has review
         *     history; otherwise drop the per-student scheduling state and remove it.
         */
        delete: operations["delete_card_in_my_deck_decks__deck_id__cards__card_id__delete"];
        options?: never;
        head?: never;
        /** Update Card In My Deck */
        patch: operations["update_card_in_my_deck_decks__deck_id__cards__card_id__patch"];
        trace?: never;
    };
    "/review/due": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Review Due
         * @description The student's queue for right now — due review cards plus rationed new cards.
         */
        get: operations["review_due_review_due_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/review/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Review Grade
         * @description Record one grade and reschedule the card via FSRS.
         */
        post: operations["review_grade_review_grade_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Quiz
         * @description A short auto-generated quiz over the student's known cards. Empty if none.
         */
        get: operations["get_quiz_quiz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quiz/answer": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Answer Quiz
         * @description Grade one quiz answer and feed the result to FSRS: a hit grades `good`, a
         *     miss grades `again` so the card comes back sooner (SoW §4).
         */
        post: operations["answer_quiz_quiz_answer_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** My Streak */
        get: operations["my_streak_me_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description Per-student progress + who's slipping (SoW §4 M6). Admin-only via the
         *     router-level dependency.
         */
        get: operations["dashboard_admin_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/decks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Decks */
        get: operations["list_decks_admin_decks_get"];
        put?: never;
        /** Create Deck */
        post: operations["create_deck_admin_decks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/decks/{deck_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cards */
        get: operations["list_cards_admin_decks__deck_id__cards_get"];
        put?: never;
        /** Create Card */
        post: operations["create_card_admin_decks__deck_id__cards_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/cards/{card_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete Card
         * @description Delete a card. Blocked once it has review history — `reviews` is an
         *     append-only log we never destroy; drop the per-student scheduling state
         *     (regenerated lazily) and remove the card only when nothing has graded it.
         */
        delete: operations["delete_card_admin_cards__card_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Card
         * @description Edit a card's fields, or move it to another deck by setting `deck_id`.
         */
        patch: operations["update_card_admin_cards__card_id__patch"];
        trace?: never;
    };
    "/admin/enrich": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrich
         * @description Draft a card with AI for the teacher to review. Nothing is saved here.
         */
        post: operations["enrich_admin_enrich_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/enrich/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Enrich Bulk
         * @description Paste-a-list enrichment: one draft per term, failures reported per row so
         *     one bad word doesn't sink the batch.
         */
        post: operations["enrich_bulk_admin_enrich_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update Student
         * @description Teacher edits to a student — including their daily new-card target.
         */
        patch: operations["update_student_admin_students__student_id__patch"];
        trace?: never;
    };
    "/admin/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign Deck */
        post: operations["assign_deck_admin_assignments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/assignments/class": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Deck To Class
         * @description Push a deck to every student at once (idempotent — reactivates existing).
         */
        post: operations["assign_deck_to_class_admin_assignments_class_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AssignedDeckOut
         * @description A deck as a student sees it — with their own due count folded in.
         *
         *     `owned` is True for a personal deck the student authored themselves, False
         *     for a teacher-assigned ("class") deck — the student can edit the former and
         *     only study the latter.
         */
        AssignedDeckOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Exam Tag */
            exam_tag?: string | null;
            /** Topic Tags */
            topic_tags: string[];
            /** Due Count */
            due_count: number;
            /** Card Count */
            card_count: number;
            /** Owned */
            owned: boolean;
        };
        /** AssignmentCreate */
        AssignmentCreate: {
            /** Student Id */
            student_id: number;
            /** Deck Id */
            deck_id: number;
            /** Daily New Target */
            daily_new_target?: number | null;
        };
        /** AssignmentOut */
        AssignmentOut: {
            /** Id */
            id: number;
            /** Student Id */
            student_id: number;
            /** Deck Id */
            deck_id: number;
            /** Daily New Target */
            daily_new_target: number | null;
            /**
             * Assigned At
             * Format: date-time
             */
            assigned_at: string;
            /** Active */
            active: boolean;
        };
        /**
         * BulkEnrichItem
         * @description One row of a paste-a-list enrichment: a draft, or an error for that term.
         */
        BulkEnrichItem: {
            /** Term */
            term: string;
            /** Meaning */
            meaning?: string | null;
            /** Ipa */
            ipa?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Error */
            error?: string | null;
        };
        /** BulkEnrichRequest */
        BulkEnrichRequest: {
            /** Terms */
            terms: string[];
        };
        /** CardCreate */
        CardCreate: {
            /** Term */
            term: string;
            /** Meaning */
            meaning: string;
            /** Ipa */
            ipa?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** @default manual */
            source: components["schemas"]["CardSource"];
        };
        /** CardOut */
        CardOut: {
            /** Id */
            id: number;
            /** Deck Id */
            deck_id: number;
            /** Term */
            term: string;
            /** Meaning */
            meaning: string;
            /** Ipa */
            ipa?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            source: components["schemas"]["CardSource"];
        };
        /**
         * CardSource
         * @enum {string}
         */
        CardSource: "manual" | "ai-enriched";
        /**
         * CardStateEnum
         * @enum {string}
         */
        CardStateEnum: "new" | "learning" | "review" | "lapsed";
        /**
         * CardUpdate
         * @description Partial edit of a card. Any field left unset is untouched; setting
         *     `deck_id` moves the card to another deck.
         */
        CardUpdate: {
            /** Term */
            term?: string | null;
            /** Meaning */
            meaning?: string | null;
            /** Ipa */
            ipa?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Deck Id */
            deck_id?: number | null;
        };
        /**
         * ClassAssignmentCreate
         * @description Assign a deck to every student at once (SoW §4 whole-class control).
         */
        ClassAssignmentCreate: {
            /** Deck Id */
            deck_id: number;
            /** Daily New Target */
            daily_new_target?: number | null;
        };
        /** CreateStudentRequest */
        CreateStudentRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /**
             * Timezone
             * @default Asia/Ho_Chi_Minh
             */
            timezone: string;
            /**
             * Daily New Target
             * @default 10
             */
            daily_new_target: number;
        };
        /** DashboardOut */
        DashboardOut: {
            /** Students */
            students: components["schemas"]["DashboardStudent"][];
            summary: components["schemas"]["DashboardSummary"];
            /** Decks */
            decks: components["schemas"]["DeckProgress"][];
        };
        /**
         * DashboardStudent
         * @description One row of the teacher's class table (SoW §4 admin dashboard).
         */
        DashboardStudent: {
            /** Id */
            id: number;
            /** Display Name */
            display_name: string;
            /** Email */
            email: string;
            /** Current Streak */
            current_streak: number;
            /** Last Active At */
            last_active_at: string | null;
            /** Days Inactive */
            days_inactive: number | null;
            /** Due Count */
            due_count: number;
            /** Reviewed Week */
            reviewed_week: number;
            /** Accuracy */
            accuracy: number | null;
            /** Slipping */
            slipping: boolean;
        };
        /** DashboardSummary */
        DashboardSummary: {
            /** Total Students */
            total_students: number;
            /** Active This Week */
            active_this_week: number;
            /** Reviewed Week */
            reviewed_week: number;
            /** Avg Accuracy */
            avg_accuracy: number | null;
            /** Slipping Count */
            slipping_count: number;
        };
        /** DeckCreate */
        DeckCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Exam Tag */
            exam_tag?: string | null;
            /**
             * Topic Tags
             * @default []
             */
            topic_tags: string[];
        };
        /** DeckOut */
        DeckOut: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Exam Tag */
            exam_tag?: string | null;
            /** Topic Tags */
            topic_tags: string[];
        };
        /**
         * DeckProgress
         * @description Per (class) deck progress — how far the assigned students have gotten.
         */
        DeckProgress: {
            /** Id */
            id: number;
            /** Name */
            name: string;
            /** Exam Tag */
            exam_tag: string | null;
            /** Card Count */
            card_count: number;
            /** Students Assigned */
            students_assigned: number;
            /** Mastered Pct */
            mastered_pct: number | null;
        };
        /** EnrichRequest */
        EnrichRequest: {
            /** Term */
            term: string;
        };
        /**
         * EnrichmentOut
         * @description An AI-drafted card the teacher reviews before saving — nothing persisted.
         */
        EnrichmentOut: {
            /** Term */
            term: string;
            /** Meaning */
            meaning: string;
            /** Ipa */
            ipa: string;
            /** Example Sentence */
            example_sentence: string;
        };
        /** GradeIn */
        GradeIn: {
            /** Card Id */
            card_id: number;
            rating: components["schemas"]["Rating"];
            /** Elapsed Ms */
            elapsed_ms?: number | null;
        };
        /**
         * GradeOut
         * @description The scheduler's verdict: when this card comes back and in what state.
         */
        GradeOut: {
            /** Card Id */
            card_id: number;
            state: components["schemas"]["CardStateEnum"];
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
            /** Reps */
            reps: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /**
         * PersonalDeckCreate
         * @description A student authoring their own deck — no exam_tag/topic_tags, which are
         *     teacher-curriculum concepts.
         */
        PersonalDeckCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
        };
        /** PersonalDeckUpdate */
        PersonalDeckUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
        };
        /** QuizAnswerIn */
        QuizAnswerIn: {
            /** Card Id */
            card_id: number;
            kind: components["schemas"]["QuizKind"];
            /** Answer */
            answer: string;
            /** Elapsed Ms */
            elapsed_ms?: number | null;
        };
        /**
         * QuizAnswerOut
         * @description The verdict for one answer. A miss feeds the scheduler as `again` so the
         *     card comes back sooner; a hit feeds it as `good` (SoW §4: quizzes feed FSRS).
         */
        QuizAnswerOut: {
            /** Card Id */
            card_id: number;
            /** Correct */
            correct: boolean;
            /** Correct Answer */
            correct_answer: string;
            state: components["schemas"]["CardStateEnum"];
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
        };
        /**
         * QuizKind
         * @description The two quiz formats from SoW §4. API-only — never persisted, so it lives
         *     here beside the request/response shapes rather than in `models/enums.py`.
         * @enum {string}
         */
        QuizKind: "mcq" | "type_answer";
        /**
         * QuizQuestion
         * @description One generated question. Only the fields the given `kind` needs are set:
         *     the correct answer is never sent — grading happens server-side in `/quiz/answer`.
         *
         *     - mcq: `term` + `ipa` shown, `options` are meanings to choose between.
         *     - type_answer: `meaning` (+ blanked `example_sentence`) shown, student types the term.
         */
        QuizQuestion: {
            /** Card Id */
            card_id: number;
            kind: components["schemas"]["QuizKind"];
            /** Term */
            term?: string | null;
            /** Ipa */
            ipa?: string | null;
            /** Meaning */
            meaning?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Options */
            options?: string[] | null;
        };
        /**
         * Rating
         * @enum {string}
         */
        Rating: "again" | "hard" | "good" | "easy";
        /**
         * RegisterRequest
         * @description Public self-signup — always creates a `student`. Role can't be chosen here;
         *     teacher accounts are still provisioned out-of-band.
         */
        RegisterRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            /** Password */
            password: string;
            /**
             * Timezone
             * @default Asia/Ho_Chi_Minh
             */
            timezone: string;
        };
        /**
         * ReviewCardOut
         * @description A due card as the student reviews it — everything the Flashcard renders.
         */
        ReviewCardOut: {
            /** Card Id */
            card_id: number;
            /** Deck Id */
            deck_id: number;
            /** Term */
            term: string;
            /** Meaning */
            meaning: string;
            /** Ipa */
            ipa?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
            /** Image Url */
            image_url?: string | null;
            /** Audio Url */
            audio_url?: string | null;
            /** Exam Tag */
            exam_tag?: string | null;
            state: components["schemas"]["CardStateEnum"];
            /**
             * Due At
             * Format: date-time
             */
            due_at: string;
        };
        /** StreakOut */
        StreakOut: {
            /** Current Streak */
            current_streak: number;
            /** Longest Streak */
            longest_streak: number;
            /** Freezes Remaining */
            freezes_remaining: number;
        };
        /**
         * StudentCardUpdate
         * @description Partial edit of a card in the student's OWN deck. No `deck_id`: a student
         *     can't move a card between decks (that could target a teacher's deck).
         */
        StudentCardUpdate: {
            /** Term */
            term?: string | null;
            /** Meaning */
            meaning?: string | null;
            /** Ipa */
            ipa?: string | null;
            /** Example Sentence */
            example_sentence?: string | null;
        };
        /**
         * StudentUpdate
         * @description Teacher edits to a student — notably the per-student daily new-card target.
         */
        StudentUpdate: {
            /** Display Name */
            display_name?: string | null;
            /** Timezone */
            timezone?: string | null;
            /** Daily New Target */
            daily_new_target?: number | null;
        };
        /**
         * TokenResponse
         * @description The refresh token is NOT in this body — it rides in an httpOnly cookie.
         */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            user: components["schemas"]["UserOut"];
        };
        /** UserOut */
        UserOut: {
            /** Id */
            id: number;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Display Name */
            display_name: string;
            role: components["schemas"]["UserRole"];
            /** Timezone */
            timezone: string;
            /** Daily New Target */
            daily_new_target: number;
        };
        /**
         * UserRole
         * @enum {string}
         */
        UserRole: "admin" | "student";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: {
                lexi_refresh?: string | null;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
        };
    };
    list_students_auth_students_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
        };
    };
    create_student_auth_students_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateStudentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_my_decks_decks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignedDeckOut"][];
                };
            };
        };
    };
    create_my_deck_decks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalDeckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignedDeckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_my_deck_decks__deck_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_my_deck_decks__deck_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PersonalDeckUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignedDeckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_deck_cards_decks__deck_id__cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_card_to_my_deck_decks__deck_id__cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_in_my_deck_decks__deck_id__cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_in_my_deck_decks__deck_id__cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    review_due_review_due_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReviewCardOut"][];
                };
            };
        };
    };
    review_grade_review_grade_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GradeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_quiz_quiz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizQuestion"][];
                };
            };
        };
    };
    answer_quiz_quiz_answer_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["QuizAnswerIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizAnswerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    my_streak_me_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakOut"];
                };
            };
        };
    };
    dashboard_admin_dashboard_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
        };
    };
    list_decks_admin_decks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOut"][];
                };
            };
        };
    };
    create_deck_admin_decks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeckCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeckOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cards_admin_decks__deck_id__cards_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_card_admin_decks__deck_id__cards_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                deck_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_card_admin_cards__card_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_card_admin_cards__card_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                card_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_admin_enrich_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrichRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enrich_bulk_admin_enrich_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkEnrichRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkEnrichItem"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_admin_students__student_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                student_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_deck_admin_assignments_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_deck_to_class_admin_assignments_class_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassAssignmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssignmentOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
