"""add streaks.last_reminded_date

Revision ID: 186fc858fb7e
Revises: 45abadc06527
Create Date: 2026-07-16 11:09:12.695046
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '186fc858fb7e'
down_revision: str | None = '45abadc06527'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('streaks', sa.Column('last_reminded_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('streaks', 'last_reminded_date')
    # ### end Alembic commands ###
